### ISSUE TITLE
An error pops while intergrating the norrisbot

### ISSUE THREAD

**Issue by SibuStephen** [lmammino/norrisbot#1]
/*npm-debug.log*/
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart norrisbot@1.0.4
6 info start norrisbot@1.0.4
7 verbose unsafe-perm in lifecycle true
8 info norrisbot@1.0.4 Failed to exec start script
9 verbose stack Error: norrisbot@1.0.4 start: `node bin/bot.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid norrisbot@1.0.4
11 verbose cwd /var/www/html/norrisbot
12 error Linux 3.16.0-46-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error norrisbot@1.0.4 start: `node bin/bot.js`
17 error Exit status 1
18 error Failed at the norrisbot@1.0.4 start script 'node bin/bot.js'.
18 error This is most likely a problem with the norrisbot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node bin/bot.js
18 error You can get their info via:
18 error     npm owner ls norrisbot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by lmammino** [comment]
Hey @SibuStephen,
Why did you closed the issue? Have you been able to sort it out on your own? If there was any kind of error you solved it would be nice to share it here as a reference for other people.

Anyway I just updated the install instructions because there was some errors in it, so the new readme should be easier to follow.

**Comment by SibuStephen** [comment]
Hey @lmammino  Yes I figured out the error, it was just because I didn't  install some of the dependencies, soon as I realized that, I closed this issue :) , but still there are some issues i'm facing which i will be Creating a new  PR or raise an issue for that as such

**Comment by lmammino** [comment]
Thanks @sibustephen, I really look forward to receiving your PR
