### ISSUE TITLE
Trying to launch the bot but nothing happens

### ISSUE THREAD

**Issue by ibiza240** [lmammino/norrisbot#2]
I am trying to make the bot run, note that I am not very skilled with npm and node yet :)
I follow the instructions and try to run the bot with the help of the `npm start` command.

Here's the output I get :

```
F:\norrisbot>npm start

> norrisbot@1.0.5 start F:\norrisbot
> node bin/bot.js


F:\norrisbot>
```

No error, but nothing happens either in the console or the slack general channel...

By the way I set up my `BOT_API_KEY` variable correctly (with the `token.js` method)

**Comment by crrobinson14** [comment]
StackOverflow discussion of the same issue - possible path formatting problem on Windows?
http://stackoverflow.com/questions/36612467/trying-to-launch-my-node-js-program-with-npm-but-nothing-happens/36637596#36637596

**Comment by someone12321** [comment]
@ibiza240 whether you tried to debug, using console.log, that where the program's flow is breaking. Try to print the message using console.log at every point. I followed this tutorial : https://scotch.io/tutorials/building-a-slack-bot-with-node-js-and-chuck-norris-super-powers
and it helped me alot to clear my doubts and concept regarding bot.

**Comment by lmammino** [comment]
Hi Guys, sorry for the very late reply. I just updated Norribot to version 2.0 using the official slack bot app and bots Node.js sdk. This version should be more stable and reliable. I won't be supporting anymore the old version, so I am closing this issue.

Feel free to open a new one if you have some issue with the new version.
