### ISSUE TITLE
Scaling question

### ISSUE THREAD

**Issue by thaiat** [lmammino/norrisbot#5]
I wonder how would you scale  your bot (or more exaclty avoid a single point of failure) ? 

Right now, if you run `heroku ps:scale worker=2` then the bot will anwser mutliple times the same message...

**Comment by lmammino** [comment]
Hello @thaiat,
I am not aware of a simple way to scale websockets communication to multiple machines/nodes. Anyway you can have a look here for a refence about how to get 600k concurrent connections in a single node on Amazon AWS: https://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/

**Comment by lmammino** [comment]
Closing this one at this stage. Also be aware that I just published Version 2 of the norrisbot, totally rewritten from scratch! :)
