### ISSUE TITLE
I run the code and Chuck is added to channel, but he doesn't talk

### ISSUE THREAD

**Issue by nickaustinlee** [lmammino/norrisbot#8]
I didn't modify any of the code, but Chuck Norris bot does not talk in Slack. I have messaged it several times, nothing!

**Comment by lmammino** [comment]
Hi @nickaustinlee, sorry for the very late reply. I just updated Norribot to version 2.0 using the official slack bot app and bots Node.js sdk. This version should be more stable and reliable. I won't be supporting anymore the old version, so I am closing this issue.

Feel free to open a new one if you have some issue with the new version.
