### ISSUE TITLE
NorrisBot is not working with nodeJS 4.2.6

### ISSUE THREAD

**Issue by nohorbee** [lmammino/norrisbot#9]
I was trying out the example on this post: https://scotch.io/tutorials/building-a-slack-bot-with-node-js-and-chuck-norris-super-powers

When I ran the bot, I got the following error:
TypeError: Class constructors cannot be invoked without 'new'
    at Constructor.Bot (/home/noberto/workspaces/norrisbot/node_modules/slackbots/index.js:16:17)
    at Constructor.NorrisBot.run (/home/noberto/workspaces/norrisbot/lib/norrisbot.js:24:20)
    at Object.<anonymous> (/home/noberto/workspaces/norrisbot/bin/bot.js:17:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

After a brief research, I found that that way of inheritance is not supported on ES6. Before changing anything else, I cloned this repo and it was working. I checked the differences and found that the package.json specifies a different Engine >=0.10 . I'm not sure if that's the problem but when I run my code with the package.json on this repository, the error is not being shown.

Is that an expected behavior? Should I rewrite the entire code of my bot to use classes and extension?

Thanks!

**Comment by lmammino** [comment]
Hello @nohorbee,
Thank you for reading the tutorial and submitting this issue.

Before moving on I would like to clarify few things:

- Did you just copy-pasted the code from the tutorial or did you tried to change it?
- Which version of node are you running?
- Are you using an updated version of the dependencies (compare it with the [`package.json` in this repo](https://github.com/lmammino/norrisbot/blob/master/package.json))?

Thanks

**Comment by nohorbee** [comment]
Hi @lmammino,

Thanks for the tutorial and the quick answer.
Regarding to your questions:
1. I did not copy and pasted. I read and typed (it helps me to fit the knowledge)
2. node version: 4.2.6
3. When I had the error, I was using the package.json mentioned on the tutorial. 
```
"engines": {
    "node": ">=0.10.0"
  },
```

That worked. So, I'm trying to figure out if it is because Utils.inherits and NorrisBoy.super._call is no longer supported in new versions of node, and if so, if I just simple need to use the 0.10.0 engine, or if I should change the code to use ES6 classes.

In any case, it would be a good thing if that can be clarified in the post (after we discover what is the problem).

Thanks again!

**Comment by lmammino** [comment]
I will need some extra investigation but my current assumption is that when you did `npm i --save slackbots` you got a new version of `slackbots` that is no longer compatible with my code base.

I'll try to clarify this and update the post in case...

Thanks again for taking the time to point this out! :)

**Comment by nohorbee** [comment]
I have just checked:
The package.json on the post says: "slackbots": "^1.0.1",
The one in your repo: "slackbots": "^0.3.0",

I made a quick test of changing it, `npm install` and running and it seemed to work (actually, I'm not checking if that worked but if the error is not being thrown anymore). That's a good clue. I will try to research on this side too, so I can come up with a code compatible with the newer versions. Let me know about your findings. I'll let you know about mines! :) 

Thanks!

**Comment by nohorbee** [comment]
I tried something additional:
1. simply put the "new" keyword before the NorrisBot.super_.call ---> worked.
2. moved that line to the NorrisBot constructor (constructor calling parent constructor).

It's going up, and it is answering to Chuck Norris. Not answering to @norrisbot, and not joining any channel by its own (needs to be invited to start listening). I'll review that this afternoon at home. The bug should be something I'm missing in my code.

Thanks for the great tutorial!

**Comment by tvtri96** [comment]
At first I did `npm install` and it throws lots of error about the conflicting version. After I updated the package.json as @nohorbee posted. Now, I have the error "TypeError: Class constructors cannot be invoked without 'new'" when trying to run the bot.

**Comment by kosmos** [comment]
I have same problem.

**Comment by tjrileywisc** [comment]
@nohorbee I ended up rewriting the NorrisBot class with extension and it worked right away, except for one odd flaw that I haven't been able to fix yet when trying to run NorrisBot's super constructor (I have to hardcode the token).

**Comment by lmammino** [comment]
Hi Guys, sorry for the very late reply. I just updated Norribot to version 2.0 using the official slack bot app and bots Node.js sdk. This version should be more stable and reliable. I won't be supporting anymore the old version, so I am closing this issue.

Feel free to open a new one if you have some issue with the new version.
